## Proyek UAS IBDA 2112 - Keamanan dan Pengelolaan Data

**Pemrograman Nomor 2 - Data Minimization & Pseudonimisasi**

Kelompok:
- Alfandi Wijaya - 232200156
- Keanrich Cordana - 232301226

Komitmen Integritas

“Di hadapan TUHAN yang hidup, saya menegaskan bahwa saya tidak memberikan maupun menerima bantuan apapun—baik lisan, tulisan, maupun elektronik—di dalam ujian ini selain daripada apa yang telah diizinkan oleh pengajar, dan tidak akan menyebarkan baik soal maupun jawaban ujian kepada pihak lain.”

## Merging

Pada bagian ini kami mengelompokkan data encounter.csv dan patient.csv pada file Dataset_Hospuital_Full yang akan kami gunakan

In [ ]:
import pandas as pd 
import base64
import numpy as np

# Merging Encounters and Patients DataFrames

# Baca data
df_encounter = pd.read_csv(".\Dataset_Hospital_Full\encounters.csv")
df_patient = pd.read_csv(".\Dataset_Hospital_Full\patients.csv")

# Rename Id pada df_patient menjadi PATIENT agar bisa merge
df_patient_renamed = df_patient.rename(columns={"Id": "PATIENT"})

# Merge berdasarkan PATIENT
df_merged = pd.merge(df_encounter, df_patient_renamed, on="PATIENT", how="inner")

# Susun kolom sesuai permintaan
desired_order = [
    "Id", "PATIENT", "BIRTHDATE", "DEATHDATE", "PREFIX", "FIRST", "LAST", "SUFFIX",
    "MAIDEN", "MARITAL", "RACE", "ETHNICITY", "GENDER", "BIRTHPLACE", "ADDRESS",
    "CITY", "STATE", "COUNTY", "ZIP", "LAT", "LON", "START", "STOP", "ORGANIZATION",
    "PAYER", "ENCOUNTERCLASS", "CODE", "DESCRIPTION", "BASE_ENCOUNTER_COST",
    "TOTAL_CLAIM_COST", "PAYER_COVERAGE", "REASONCODE", "REASONDESCRIPTION"
]

# Susun dataframe dengan urutan kolom tersebut
df_final = df_merged[desired_order]

# Mabatasi jumlah baris menjadi 10000 Untuk kepentingan pengumpulan ke moodle Agar size file tidak terlalu besar
df_final = df_final.head(10000)

## Data Minimization

Pada bagian ini kamu menghapus data-data PII yang dinilai terlalu banyak atau inrelevan. Data tersebut adalah kolom "ORGANIZATION", 'PAYER', "PATIENT", "SUFFIX", "REASONCODE", "CODE",'BIRTHPLACE', 'STATE', 'COUNTY', 'ETHNICITY',  'LAT', 'LON', 'ZIP', 'RACE', 'DEATHDATE'.

In [7]:
# Data Minimization 

# Menghapus data-data irrelevan yang tidak dapat diolah
kolom_kode_not_defined = ["ORGANIZATION", 'PAYER', "PATIENT", "SUFFIX", "REASONCODE", "CODE"]
data = df_final.drop(columns=[col for col in kolom_kode_not_defined if col in df_final.columns], errors='ignore')
display(data)

# Meminimalisir penganmbilan data dengan Menghapus data-data PII 
kolom_pii = ['BIRTHPLACE' ,'STATE', 'COUNTY', 'ETHNICITY',  'LAT', 'LON', 'ZIP', 'RACE', 'DEATHDATE']
data = data.drop(columns=[col for col in kolom_pii if col in data.columns], errors='ignore')
display(data)

,Id,BIRTHDATE,DEATHDATE,PREFIX,FIRST,LAST,MAIDEN,MARITAL,RACE,ETHNICITY,...,LAT,LON,START,STOP,ENCOUNTERCLASS,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,1928-08-25,2017-02-04,Mr.,Mariano761,O'Kon634,NaN,M,white,nonhispanic,...,42.358161,-71.037766,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,ambulatory,Encounter for problem (procedure),85.55,1018.02,0.00,NaN
1,c98059da-320a-c0a6-fced-c8815f3e3f39,1964-01-05,2020-06-02,Mrs.,Myrtis608,Lindgren255,Anderson154,M,white,nonhispanic,...,42.348269,-71.042251,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,outpatient,Patient encounter procedure,142.58,2619.36,0.00,NaN
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,1924-06-30,NaN,Mrs.,Marianne327,Nienow652,White193,M,asian,nonhispanic,...,42.310534,-71.028506,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,outpatient,Encounter for check up (procedure),85.55,461.59,305.27,NaN
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,1923-05-21,2021-01-04,Mr.,Efrain317,Dibbert990,NaN,M,white,nonhispanic,...,42.362921,-71.013067,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,wellness,General examination of patient (procedure),136.80,1784.24,0.00,NaN
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,1952-11-02,NaN,Mr.,Emerson869,Kreiger457,NaN,M,white,nonhispanic,...,42.251939,-70.990535,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,ambulatory,Follow-up encounter,85.55,234.72,0.00,Hyperlipidemia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ece652ba-a014-195a-f18e-adc00af23e70,1990-09-22,NaN,Mrs.,Candi549,Hane680,Thompson596,M,white,nonhispanic,...,42.356862,-71.034368,2015-01-26T20:49:35Z,2015-01-26T21:04:35Z,outpatient,Consultation for treatment,142.58,157.00,0.00,NaN
9996,56de3587-aaf1-7e01-9f46-d3a2b8afb376,1933-09-02,NaN,Mrs.,Shani239,Parisian75,Kshlerin58,M,white,nonhispanic,...,42.228814,-70.921669,2015-01-27T06:52:02Z,2015-01-27T07:07:02Z,ambulatory,Encounter for symptom,85.55,1885.61,1459.18,Streptococcal sore throat (disorder)
9997,5c3ab375-5713-4644-bdee-58877dc3efdc,1938-03-26,NaN,Ms.,Cheryl605,Rempel203,NaN,S,white,nonhispanic,...,42.342610,-71.053540,2015-01-27T06:57:42Z,2015-01-27T07:57:42Z,emergency,Emergency room admission (procedure),146.18,152.30,84.94,NaN
9998,dfdb0879-0c7b-2f92-0de8-eb6a3a810ffe,1961-03-28,NaN,Ms.,Dani520,Hirthe744,NaN,S,hawaiian,nonhispanic,...,42.358561,-71.018906,2015-01-27T12:55:19Z,2015-01-27T13:55:19Z,emergency,Emergency room admission (procedure),146.18,146.18,0.00,NaN
9999,e18a087f-1fd0-3dca-1551-89fdcf0b4f75,1972-06-27,NaN,Mr.,Lowell343,Price929,NaN,M,white,nonhispanic,...,42.297904,-71.015983,2015-01-27T16:35:51Z,2015-01-27T16:50:51Z,outpatient,Encounter for check up (procedure),85.55,221.55,0.00,NaN

,Id,BIRTHDATE,PREFIX,FIRST,LAST,MAIDEN,MARITAL,GENDER,ADDRESS,CITY,START,STOP,ENCOUNTERCLASS,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,1928-08-25,Mr.,Mariano761,O'Kon634,NaN,M,M,531 Little Crossing,Boston,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,ambulatory,Encounter for problem (procedure),85.55,1018.02,0.00,NaN
1,c98059da-320a-c0a6-fced-c8815f3e3f39,1964-01-05,Mrs.,Myrtis608,Lindgren255,Anderson154,M,F,860 Goldner Trailer,Boston,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,outpatient,Patient encounter procedure,142.58,2619.36,0.00,NaN
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,1924-06-30,Mrs.,Marianne327,Nienow652,White193,M,F,760 Klein Rue Apt 38,Boston,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,outpatient,Encounter for check up (procedure),85.55,461.59,305.27,NaN
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,1923-05-21,Mr.,Efrain317,Dibbert990,NaN,M,M,475 Wunsch Overpass,Boston,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,wellness,General examination of patient (procedure),136.80,1784.24,0.00,NaN
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,1952-11-02,Mr.,Emerson869,Kreiger457,NaN,M,M,586 Torphy Burg,Braintree,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,ambulatory,Follow-up encounter,85.55,234.72,0.00,Hyperlipidemia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ece652ba-a014-195a-f18e-adc00af23e70,1990-09-22,Mrs.,Candi549,Hane680,Thompson596,M,F,476 Price Bypass,Cambridge,2015-01-26T20:49:35Z,2015-01-26T21:04:35Z,outpatient,Consultation for treatment,142.58,157.00,0.00,NaN
9996,56de3587-aaf1-7e01-9f46-d3a2b8afb376,1933-09-02,Mrs.,Shani239,Parisian75,Kshlerin58,M,F,188 Torp Gateway,Weymouth,2015-01-27T06:52:02Z,2015-01-27T07:07:02Z,ambulatory,Encounter for symptom,85.55,1885.61,1459.18,Streptococcal sore throat (disorder)
9997,5c3ab375-5713-4644-bdee-58877dc3efdc,1938-03-26,Ms.,Cheryl605,Rempel203,NaN,S,F,1006 Mills Drive,Somerville,2015-01-27T06:57:42Z,2015-01-27T07:57:42Z,emergency,Emergency room admission (procedure),146.18,152.30,84.94,NaN
9998,dfdb0879-0c7b-2f92-0de8-eb6a3a810ffe,1961-03-28,Ms.,Dani520,Hirthe744,NaN,S,F,684 Weissnat Union Apt 86,Boston,2015-01-27T12:55:19Z,2015-01-27T13:55:19Z,emergency,Emergency room admission (procedure),146.18,146.18,0.00,NaN
9999,e18a087f-1fd0-3dca-1551-89fdcf0b4f75,1972-06-27,Mr.,Lowell343,Price929,NaN,M,M,694 Kuhlman Corner Apt 74,Quincy,2015-01-27T16:35:51Z,2015-01-27T16:50:51Z,outpatient,Encounter for check up (procedure),85.55,221.55,0.00,NaN

## Pseudonimization 

Pada bagian ini kamu mengenkripsi data PII yang dinilai penting dan tidak boleh untuk diketahui umum taitu Kolom "FIRST","LAST","BIRTHDATE","MAIDEN","ADDRESS".

In [8]:
# Pseudonimization 

def encode1(key, clear):
    key_len = len(key)
    key_ord = np.array([ord(k) for k in key])  # Precompute ord for key once
    clear_ord = np.array([ord(c) for c in clear])  # Precompute ord for clear text once
    enc_ord = (clear_ord + key_ord[np.tile(np.arange(key_len), len(clear)//key_len + 1)[:len(clear)]]) % 256
    return base64.urlsafe_b64encode(enc_ord.astype(np.uint8)).decode('utf-8')


#Fungsi Untuk mendekripsi data yang sudah dienkripsi
def decode1(key, enc):
    key_len = len(key)
    key_ord = np.array([ord(k) for k in key])
    enc_bytes = np.frombuffer(base64.urlsafe_b64decode(enc), dtype=np.uint8)
    clear_ord = (enc_bytes - key_ord[np.tile(np.arange(key_len), len(enc_bytes) // key_len + 1)[:len(enc_bytes)]] + 256) % 256
    return ''.join(map(chr, clear_ord))


# Melakukan enkripsi pada data-data PII yang tersisa
data["FIRST"] = data["FIRST"].apply(lambda name: encode1("secret key", str(name)))
data["BIRTHDATE"] = data["BIRTHDATE"].apply(lambda name: encode1("secret key", str(name)))
data["LAST"] = data["LAST"].apply(lambda name: encode1("secret key", str(name)))
data["MAIDEN"] = data["MAIDEN"].apply(lambda name: encode1("secret key", str(name)))
data["ADDRESS"] = data["ADDRESS"].apply(lambda name: encode1("secret key", str(name)))
display(data)

,Id,BIRTHDATE,PREFIX,FIRST,LAST,MAIDEN,MARITAL,GENDER,ADDRESS,CITY,START,STOP,ENCOUNTERCLASS,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,pJ6VqpKkWJiXrg==,Mr.,wMbV28bij6Kbqg==,woyu4dOqU58=,4cbR,M,M,qJiUkrHdlN_R3pOo1eHY54nZzA==,Boston,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,ambulatory,Encounter for problem (procedure),85.55,1018.02,0.00,NaN
1,c98059da-320a-c0a6-fced-c8815f3e3f39,pJ6ZppKkUZiVrg==,Mrs.,wN7V5s7nVpud,v87R1szmhdmXrqg=,tNPH19fnj9mWrqc=,M,F,q5uTkqzjjM_T3uWFt-TG3YzQ1w==,Boston,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,outpatient,Patient encounter procedure,142.58,2619.36,0.00,NaN
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,pJ6VppKkVpiYqQ==,Mrs.,wMbV28bijtCYq6o=,wc7I4NTrVqCX,ys3M5sqlWZ4=,M,F,qpuTkrDghdTTmcXayJKm5JSLmLE=,Boston,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,outpatient,Encounter for check up (procedure),85.55,461.59,305.27,NaN
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,pJ6VpZKkVZiXqg==,Mr.,uMvV087iU5yc,t87F1MrmlKSeqQ==,4cbR,M,M,p5yYkrzpjt7I4ZO02dfX5IHe2A==,Boston,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,wellness,General examination of patient (procedure),136.80,1784.24,0.00,NaN
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,pJ6YpJKlUZiVqw==,Mr.,uNLI5NjjjqObsg==,vtfI28zZkp-asA==,4cbR,M,M,qJ2ZkrnjktvN8pOn2OTM,Braintree,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,ambulatory,Follow-up encounter,85.55,234.72,0.00,Hyperlipidemia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ece652ba-a014-195a-f18e-adc00af23e70,pJ6copKkWZiXqw==,Mrs.,tsbR1s6pVKQ=,u8bR15usUA==,x83S39Xnj9masqk=,M,F,p5yZkrXmic7KmbXe09PY5w==,Cambridge,2015-01-26T20:49:35Z,2015-01-26T21:04:35Z,outpatient,Consultation for treatment,142.58,157.00,0.00,NaN
9996,56de3587-aaf1-7e01-9f46-d3a2b8afb376,pJ6WpZKkWZiVqw==,Mrs.,xs3E4M6mU6Q=,w8bV29jdgdmcrg==,vtjL3srmidmasQ==,M,F,pJ2bkrnjktuFwNTZyOnG7Q==,Weymouth,2015-01-27T06:52:02Z,2015-01-27T07:07:02Z,ambulatory,Encounter for symptom,85.55,1885.61,1459.18,Streptococcal sore throat (disorder)
9997,5c3ab375-5713-4644-bdee-58877dc3efdc,pJ6WqpKkU5iXrw==,Ms.,ts3I5N7gVpua,xcrQ4srgUpuY,4cbR,S,F,pJWTqIXBidfR7JOp1dvb2Q==,Somerville,2015-01-27T06:57:42Z,2015-01-27T07:57:42Z,emergency,Emergency room admission (procedure),146.18,152.30,84.94,NaN
9998,dfdb0879-0c7b-2f92-0de8-eb6a3a810ffe,pJ6Zo5KkU5iXsQ==,Ms.,t8bR25qmUA==,u87V5s3ZV5-Z,4cbR,S,F,qZ2XkrzZid7Y59TZg8fT3Y_Zhbrj2YOqmw==,Boston,2015-01-27T12:55:19Z,2015-01-27T13:55:19Z,emergency,Emergency room admission (procedure),146.18,146.18,0.00,NaN
9999,e18a087f-1fd0-3dca-1551-89fdcf0b4f75,pJ6apJKkVpiXsA==,Mr.,v9Ta19HgU5-Y,w9fM1cqtUqQ=,4cbR,M,M,qZ6XkrDpiNfS2uGFpuHX4oXdhbrj2YOpmQ==,Quincy,2015-01-27T16:35:51Z,2015-01-27T16:50:51Z,outpatient,Encounter for check up (procedure),85.55,221.55,0.00,NaN

Kami juga melakukan penimpaan data dengan mengganti data tersebut dengan hal lain untuk mengamankan data

In [9]:
# masking => melakukan penimpaan dat  
def masking (kolom, variabel):
    data[kolom] = variabel
    return data

# menyembunyikan identitas pasien seperti gender, penyakit dan lain-lain
data_ingin_disembunyikan = [("PREFIX", "M/F"), ("GENDER", "M/F"), ("START", "datetime"), 
                            ("STOP", "satetime"), ("REASONDESCRIPTION", "ILLNESS"), ("ENCOUNTERCLASS", 'CLASS'), 
                            ("DESCRIPTION", "DESCRIPTION")]
for column in data_ingin_disembunyikan:
    masking(column[0], column[1])

display(data)
data.to_csv("safe_data.csv", index=False)

,Id,BIRTHDATE,PREFIX,FIRST,LAST,MAIDEN,MARITAL,GENDER,ADDRESS,CITY,START,STOP,ENCOUNTERCLASS,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,pJ6VqpKkWJiXrg==,M/F,wMbV28bij6Kbqg==,woyu4dOqU58=,4cbR,M,M/F,qJiUkrHdlN_R3pOo1eHY54nZzA==,Boston,datetime,satetime,CLASS,DESCRIPTION,85.55,1018.02,0.00,ILLNESS
1,c98059da-320a-c0a6-fced-c8815f3e3f39,pJ6ZppKkUZiVrg==,M/F,wN7V5s7nVpud,v87R1szmhdmXrqg=,tNPH19fnj9mWrqc=,M,M/F,q5uTkqzjjM_T3uWFt-TG3YzQ1w==,Boston,datetime,satetime,CLASS,DESCRIPTION,142.58,2619.36,0.00,ILLNESS
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,pJ6VppKkVpiYqQ==,M/F,wMbV28bijtCYq6o=,wc7I4NTrVqCX,ys3M5sqlWZ4=,M,M/F,qpuTkrDghdTTmcXayJKm5JSLmLE=,Boston,datetime,satetime,CLASS,DESCRIPTION,85.55,461.59,305.27,ILLNESS
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,pJ6VpZKkVZiXqg==,M/F,uMvV087iU5yc,t87F1MrmlKSeqQ==,4cbR,M,M/F,p5yYkrzpjt7I4ZO02dfX5IHe2A==,Boston,datetime,satetime,CLASS,DESCRIPTION,136.80,1784.24,0.00,ILLNESS
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,pJ6YpJKlUZiVqw==,M/F,uNLI5NjjjqObsg==,vtfI28zZkp-asA==,4cbR,M,M/F,qJ2ZkrnjktvN8pOn2OTM,Braintree,datetime,satetime,CLASS,DESCRIPTION,85.55,234.72,0.00,ILLNESS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ece652ba-a014-195a-f18e-adc00af23e70,pJ6copKkWZiXqw==,M/F,tsbR1s6pVKQ=,u8bR15usUA==,x83S39Xnj9masqk=,M,M/F,p5yZkrXmic7KmbXe09PY5w==,Cambridge,datetime,satetime,CLASS,DESCRIPTION,142.58,157.00,0.00,ILLNESS
9996,56de3587-aaf1-7e01-9f46-d3a2b8afb376,pJ6WpZKkWZiVqw==,M/F,xs3E4M6mU6Q=,w8bV29jdgdmcrg==,vtjL3srmidmasQ==,M,M/F,pJ2bkrnjktuFwNTZyOnG7Q==,Weymouth,datetime,satetime,CLASS,DESCRIPTION,85.55,1885.61,1459.18,ILLNESS
9997,5c3ab375-5713-4644-bdee-58877dc3efdc,pJ6WqpKkU5iXrw==,M/F,ts3I5N7gVpua,xcrQ4srgUpuY,4cbR,S,M/F,pJWTqIXBidfR7JOp1dvb2Q==,Somerville,datetime,satetime,CLASS,DESCRIPTION,146.18,152.30,84.94,ILLNESS
9998,dfdb0879-0c7b-2f92-0de8-eb6a3a810ffe,pJ6Zo5KkU5iXsQ==,M/F,t8bR25qmUA==,u87V5s3ZV5-Z,4cbR,S,M/F,qZ2XkrzZid7Y59TZg8fT3Y_Zhbrj2YOqmw==,Boston,datetime,satetime,CLASS,DESCRIPTION,146.18,146.18,0.00,ILLNESS
9999,e18a087f-1fd0-3dca-1551-89fdcf0b4f75,pJ6apJKkVpiXsA==,M/F,v9Ta19HgU5-Y,w9fM1cqtUqQ=,4cbR,M,M/F,qZ6XkrDpiNfS2uGFpuHX4oXdhbrj2YOpmQ==,Quincy,datetime,satetime,CLASS,DESCRIPTION,85.55,221.55,0.00,ILLNESS